export const WatchesData = [
  // 50 sample watch items. Images reuse watch1..watch8 (cycle) so you can display images without
  // having 50 distinct image files. Replace paths if you add more assets.
  {
    id: 1,
    name: 'Astra Chrono',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'Stainless steel case, sapphire crystal, 50m water resistant.',
    description: 'Astra Chrono blends classic chronograph styling with modern reliability. The stainless steel case and sapphire crystal ensure durability, while the precise quartz chronograph movement provides accurate timing. Comfortable on the wrist and designed for everyday wear, it pairs well with both casual and formal outfits.',
    price: 249.99,
    currency: 'USD',
  },
  {
    id: 2,
    name: 'Lumen Sport',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'Lightweight silicone strap, luminous hands, activity tracking.',
    description: 'Lumen Sport is built for active lifestyles — lightweight, water resistant and equipped with luminous hands for low-light visibility. Its silicone strap provides long-lasting comfort during workouts, and the integrated activity tracking features make it a practical companion for training. The balanced dial design keeps information readable at a glance.',
    price: 129.0,
    currency: 'USD',
  },
  {
    id: 3,
    name: 'Heritage Classic',
    image: require('../images/watches/watch3.jpg'),
    short_description: 'Leather strap, vintage dial, automatic movement.',
    description: 'Heritage Classic evokes timeless elegance with a vintage-inspired dial and stitched leather strap. Its automatic movement delivers smooth operation and showcases traditional watchmaking craftsmanship. Ideal for collectors and anyone who appreciates a refined, understated aesthetic that matures beautifully with wear.',
    price: 399.5,
    currency: 'USD',
  },
  {
    id: 4,
    name: 'Orbit Minimal',
    image: require('../images/watches/watch4.jpg'),
    short_description: 'Ultra-thin case with minimalist index, mesh band.',
    description: 'Orbit Minimal focuses on essential form and function: an ultra-thin case, minimalist hour indices and a comfortable mesh band. This piece is engineered for those who prefer a sleek profile and modern restraint. Its slim silhouette fits well under shirt cuffs while keeping a strong design presence.',
    price: 179.0,
    currency: 'USD',
  },
  {
    id: 5,
    name: 'Rover Tactical',
    image: require('../images/watches/watch5.jpg'),
    short_description: 'Rugged build, compass bezel, 100m water resistance.',
    description: 'Rover Tactical is a field-ready watch with a robust case, compass bezel and 100m water resistance for outdoor use. Built to withstand rough conditions, it features a legible dial and easy-to-grip bezel for quick orientation. Perfect for hikers, campers and anyone who spends time off the beaten path.',
    price: 219.99,
    currency: 'USD',
  },
  {
    id: 6,
    name: 'Nova Smart',
    image: require('../images/watches/watch6.jpg'),
    short_description: 'Touchscreen, heart-rate sensor, notifications.',
    description: 'Nova Smart brings smartwatch convenience to your wrist: a responsive touchscreen, heart-rate sensing and notification support keep you connected and informed. The watch balances tech features with a restrained look so it transitions from workouts to meetings easily. Battery life is optimized for daily use.',
    price: 159.99,
    currency: 'USD',
  },
  {
    id: 7,
    name: 'Eclipse Luxury',
    image: require('../images/watches/watch7.jpg'),
    short_description: 'Gold-plated bezel, mother-of-pearl dial, premium leather.',
    description: 'Eclipse Luxury is designed as an elegant statement: gold-plated bezel, mother-of-pearl dial and premium leather strap create an opulent impression. The refined finishing and attention to detail make it suitable for formal occasions or elevated daily wear. Its luxurious materials are selected to age gracefully with care.',
    price: 699.0,
    currency: 'USD',
  },
  {
    id: 8,
    name: 'Trail Runner',
    image: require('../images/watches/watch11.jpg'),
    short_description: 'GPS tracking, durable polymer case, long battery life.',
    description: 'Trail Runner is focused on endurance and reliability: GPS tracking, rugged polymer case and extended battery life support long excursions. Navigation features and durable construction make it an excellent companion for trail runs and multi-day adventures. The ergonomic strap and tough display ensure comfort and resilience.',
    price: 189.5,
    currency: 'USD',
  },
  {
    id: 9,
    name: 'Astra Chrono II',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'Improved movement with enhanced chronograph functions.',
    description: 'Astra Chrono II upgrades the original with enhanced chronograph features and improved movement accuracy. Ideal for timing activities, it combines a sport-oriented dial layout with refined case finishing. The watch balances functionality with a tasteful appearance suitable for both casual and semi-formal wear.',
    price: 279.99,
    currency: 'USD',
  },
  {
    id: 10,
    name: 'Lumen Sport Pro',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'Pro fitness tracking with extended battery life.',
    description: 'Lumen Sport Pro adds advanced fitness tracking and extended battery life to the Lumen family. With improved sensors and a durable strap, this model supports serious training while keeping the interface intuitive. Water resistance and a ruggedized build make it suitable for a variety of sports.',
    price: 159.0,
    currency: 'USD',
  },
  {
    id: 11,
    name: 'Heritage Classic Rose',
    image: require('../images/watches/watch3.jpg'),
    short_description: 'Rose-gold accents and stitched leather strap.',
    description: 'Heritage Classic Rose blends vintage mechanics with modern styling — rose-gold accents, stitched leather strap and a balanced dial. The automatic movement adds horological appeal while the warm colorway brings a refined, contemporary feel. A great choice for those who prefer classic lines with a touch of warmth.',
    price: 429.5,
    currency: 'USD',
  },
  {
    id: 12,
    name: 'Orbit Minimal Slate',
    image: require('../images/watches/watch4.jpg'),
    short_description: 'Matte finish with minimalist dial; great for daily wear.',
    description: 'Orbit Minimal Slate is understated and versatile, featuring a matte-finish case and restrained dial. Its minimalist approach emphasizes clarity and comfort, making it a reliable everyday piece. The low-profile design suits both casual and office attire for an effortless look.',
    price: 189.0,
    currency: 'USD',
  },
  {
    id: 13,
    name: 'Rover Tactical MK2',
    image: require('../images/watches/watch5.jpg'),
    short_description: 'Reinforced case and tactical strap.',
    description: 'Rover Tactical MK2 improves durability with a reinforced case and tactical strap engineered for heavy use. The watch includes practical features like highly legible markers and an impact-resistant crystal. Designed for demanding environments, it is both functional and dependable.',
    price: 239.99,
    currency: 'USD',
  },
  {
    id: 14,
    name: 'Nova Smart Lite',
    image: require('../images/watches/watch6.jpg'),
    short_description: 'Compact smart watch with essential sensors.',
    description: 'Nova Smart Lite trims the feature set to the essentials in a compact, comfortable package. It offers activity monitoring, notification previews and basic health metrics while maximizing battery life. Ideal for users who want smartwatch conveniences without the bulk.',
    price: 129.99,
    currency: 'USD',
  },
  {
    id: 15,
    name: 'Eclipse Luxury Mini',
    image: require('../images/watches/watch7.jpg'),
    short_description: 'Smaller case for a refined, elegant fit.',
    description: 'Eclipse Luxury Mini preserves high-end materials in a smaller, more refined case size. It offers the same elegant details — plated bezel and premium dial — in a compact footprint for those who prefer subtle sophistication. The carefully selected strap complements the delicate proportions.',
    price: 649.0,
    currency: 'USD',
  },
  {
    id: 16,
    name: 'Trail Runner GPS',
    image: require('../images/watches/watch11.jpg'),
    short_description: 'Dedicated GPS for trail runners with altimeter.',
    description: 'Trail Runner GPS provides accurate route tracking and an integrated altimeter for outdoor athletes. Built with rugged components, it delivers reliable performance and clear mapping feedback during longer outings. The ergonomics and strap design reduce chafing during extended activity.',
    price: 219.5,
    currency: 'USD',
  },
  {
    id: 17,
    name: 'Astra Metro',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'City-style watch with polished bezel.',
    description: 'Astra Metro is tailored for urban lifestyles: polished bezel, smart case proportions and a versatile strap. The watch balances dressy and casual elements for easy transition from daytime meetings to evening events. Its refined finishing adds subtle elegance to everyday attire.',
    price: 199.99,
    currency: 'USD',
  },
  {
    id: 18,
    name: 'Lumen Night',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'High-visibility dial for night use.',
    description: 'Lumen Night emphasizes nighttime visibility with enhanced lume on hands and markers for quick reading in dark conditions. Designed for late-shift workers and night-time adventurers, it combines practicality with a sporty look. The robust case makes it suitable for active use.',
    price: 139.0,
    currency: 'USD',
  },
  {
    id: 19,
    name: 'Heritage Gold',
    image: require('../images/watches/watch3.jpg'),
    short_description: 'Gold-plated accents and vintage-inspired hands.',
    description: 'Heritage Gold channels heirloom style with gold-plated accents and vintage-inspired hands. The watch pairs classic proportions with modern reliability, offering a warm palette that stands out in formal settings. Its attention to decorative details elevates everyday dress.',
    price: 499.5,
    currency: 'USD',
  },
  {
    id: 20,
    name: 'Orbit Minimal Terra',
    image: require('../images/watches/watch4.jpg'),
    short_description: 'Earth-toned dial with matching mesh strap.',
    description: 'Orbit Minimal Terra features earth-toned aesthetics and a comfortable mesh strap, bringing a natural palette to minimalist design. The watch is subtle yet distinctive, with an emphasis on wearable comfort and visual calm. It works well as an understated style anchor.',
    price: 199.0,
    currency: 'USD',
  },
  {
    id: 21,
    name: 'Rover Field',
    image: require('../images/watches/watch5.jpg'),
    short_description: 'Field-watch styling with durable straps.',
    description: 'Rover Field offers classic field-watch robustness with modern materials and a durable strap. Its clear dial and rugged case make it reliable for outdoor tasks while retaining a handsome, utilitarian aesthetic. The watch is a practical all-rounder for daily carry.',
    price: 179.99,
    currency: 'USD',
  },
  {
    id: 22,
    name: 'Nova Connect',
    image: require('../images/watches/watch6.jpg'),
    short_description: 'Smartwatch with Bluetooth calling support.',
    description: 'Nova Connect elevates the smartwatch experience with Bluetooth calling, message previews and fitness tracking. The interface is designed for quick interactions, and the device integrates smoothly with smartphones. It is a strong choice for users who value connectivity and compact design.',
    price: 199.99,
    currency: 'USD',
  },
  {
    id: 23,
    name: 'Eclipse Pearl',
    image: require('../images/watches/watch7.jpg'),
    short_description: 'Mother-of-pearl dial with refined markers.',
    description: 'Eclipse Pearl is a feminine and refined timepiece, featuring a mother-of-pearl dial and delicate markers. The combination of luxe materials and careful finishing produces a graceful watch suitable for special occasions or elevated daily wear. Its polished case complements dress ensembles beautifully.',
    price: 749.0,
    currency: 'USD',
  },
  {
    id: 24,
    name: 'Trail Runner Pro',
    image: require('../images/watches/watch11.jpg'),
    short_description: 'Pro edition with extended battery and lap tracking.',
    description: 'Trail Runner Pro is built for serious athletes — extended battery, lap tracking and durable components help support heavy training loads. The watch provides reliable performance and precise metrics while keeping the interface focused and usable during activities. Rugged yet comfortable for long sessions.',
    price: 259.5,
    currency: 'USD',
  },
  {
    id: 25,
    name: 'Astra Sport',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'Sporty look with cushioned strap.',
    description: 'Astra Sport combines a sporty aesthetic with practical comfort — a cushioned strap and robust case construction. It is suitable for gym sessions and weekend activities, delivering a dynamic look without sacrificing everyday wearability. Easy-to-read indices make timing simple during movement.',
    price: 159.99,
    currency: 'USD',
  },
  {
    id: 26,
    name: 'Lumen Runner',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'Running metrics and lap timer.',
    description: 'Lumen Runner focuses on running performance with lap timing and dedicated metrics for pace and distance. Lightweight construction and a breathable strap reduce fatigue during workouts. Its readable display and simple controls help athletes stay focused on training.',
    price: 149.0,
    currency: 'USD',
  },
  {
    id: 27,
    name: 'Heritage Automatic',
    image: require('../images/watches/watch3.jpg'),
    short_description: 'Self-winding automatic movement, exhibition caseback.',
    description: 'Heritage Automatic showcases horological craftsmanship with a self-winding movement and exhibition caseback that reveals the rotor and movement finishing. Its classic lines and thoughtfully chosen materials make it a standout for watch enthusiasts. Elegance and mechanical charm are central to its identity.',
    price: 459.5,
    currency: 'USD',
  },
  {
    id: 28,
    name: 'Orbit Minimal Pearl',
    image: require('../images/watches/watch4.jpg'),
    short_description: 'Delicate dial ideal for formal occasions.',
    description: 'Orbit Minimal Pearl is a delicate, dress-ready watch with a refined dial and slim case. Designed to complement formal wear, it offers subtle sophistication and reliable timekeeping. Its minimal silhouette keeps the focus on clean lines and tasteful detail.',
    price: 189.0,
    currency: 'USD',
  },
  {
    id: 29,
    name: 'Rover Adventure',
    image: require('../images/watches/watch5.jpg'),
    short_description: 'Adventure-ready with shock resistance.',
    description: 'Rover Adventure is constructed for rugged journeys with shock-resistant components and a tough exterior. The watch’s features prioritize durability and legibility in challenging situations, while the strap system secures it comfortably during active use. It pairs practical engineering with confident styling.',
    price: 259.99,
    currency: 'USD',
  },
  {
    id: 30,
    name: 'Nova Fit',
    image: require('../images/watches/watch6.jpg'),
    short_description: 'Fitness-first smartwatch with multiple sport modes.',
    description: 'Nova Fit emphasizes multi-sport tracking and an intuitive interface for fitness-focused users. Multiple sport modes, reliable sensors and a lightweight chassis make it a tool for diverse workouts. The watch is tuned to provide quick metrics and encourage activity consistency.',
    price: 139.99,
    currency: 'USD',
  },
  {
    id: 31,
    name: 'Eclipse Grande',
    image: require('../images/watches/watch7.jpg'),
    short_description: 'Large-dial luxury piece with premium finishes.',
    description: 'Eclipse Grande is a bold luxury watch with a large dial and premium finishing touches. Its substantial presence is matched by refined materials and precise detailing, making it suitable for those who prefer a commanding wrist presence. The watch balances showmanship with refined craftsmanship.',
    price: 799.0,
    currency: 'USD',
  },
  {
    id: 32,
    name: 'Trail Ultra',
    image: require('../images/watches/watch11.jpg'),
    short_description: 'Ultra-durable construction for long expeditions.',
    description: 'Trail Ultra is engineered for extreme endurance with ultra-durable materials and long battery endurance. Ideal for extended expeditions, it provides dependable performance and straightforward navigation features. Practical ergonomics ensure comfort during prolonged wear in remote conditions.',
    price: 289.5,
    currency: 'USD',
  },
  {
    id: 33,
    name: 'Astra Vintage',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'Vintage-inspired styling with modern reliability.',
    description: 'Astra Vintage captures retro design cues while offering modern build quality and reliable movement. The watch is perfect for those who appreciate nostalgic aesthetics paired with contemporary durability. Subtle aging and warm tones lend it an authentic classic feel.',
    price: 219.99,
    currency: 'USD',
  },
  {
    id: 34,
    name: 'Lumen Active',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'Active lifestyle watch with water resistance.',
    description: 'Lumen Active is tailored for day-to-day activity and light water exposure with solid water resistance and a resilient strap. Its dial design emphasizes legibility and quick access to core information. The watch is an excellent option for those seeking a dependable daily companion.',
    price: 119.0,
    currency: 'USD',
  },
  {
    id: 35,
    name: 'Heritage Sport',
    image: require('../images/watches/watch3.jpg'),
    short_description: 'Blends classic looks with sporty performance.',
    description: 'Heritage Sport bridges classic styling and modern sport functionality. With reinforced components and a sporty strap, it stands up to activity while retaining a refined dial aesthetic. A versatile choice for those who want both heritage looks and practicality.',
    price: 349.5,
    currency: 'USD',
  },
  {
    id: 36,
    name: 'Orbit Minimal Black',
    image: require('../images/watches/watch4.jpg'),
    short_description: 'All-black minimal watch for a sleek look.',
    description: 'Orbit Minimal Black offers a stealthy, all-black finish for a contemporary and bold minimalist statement. The monochrome approach emphasizes silhouette and texture, creating a striking yet versatile look. It’s an ideal accessory for modern wardrobes.',
    price: 199.0,
    currency: 'USD',
  },
  {
    id: 37,
    name: 'Rover Scout',
    image: require('../images/watches/watch5.jpg'),
    short_description: 'Lightweight scouting watch with compass bezel.',
    description: 'Rover Scout features a compass bezel and a lightweight case tailored for scouts and outdoor explorers. Designed for mobility and ease of use, it pairs practical navigation cues with comfortable wearability. The watch performs well in varied conditions and supports active routines.',
    price: 199.99,
    currency: 'USD',
  },
  {
    id: 38,
    name: 'Nova Core',
    image: require('../images/watches/watch6.jpg'),
    short_description: 'Reliable core features in a slim package.',
    description: 'Nova Core concentrates on essential smartwatch features in a slim, unobtrusive package. Notifications, basic activity tracking and a clean design make it an approachable entry point to connected watches. Its minimalist interface is friendly for everyday users.',
    price: 129.99,
    currency: 'USD',
  },
  {
    id: 39,
    name: 'Eclipse Midnight',
    image: require('../images/watches/watch7.jpg'),
    short_description: 'Dark dial with luminous markers and refined strap.',
    description: 'Eclipse Midnight is refined and dramatic, with a dark dial accented by luminous markers for legibility in low light. The refined strap and polished case detail add a touch of luxury, making it suitable for evening wear and formal occasions.',
    price: 719.0,
    currency: 'USD',
  },
  {
    id: 40,
    name: 'Trail Pace',
    image: require('../images/watches/watch11.jpg'),
    short_description: 'Pace-focused runner watch with interval training modes.',
    description: 'Trail Pace targets runners with interval training modes and ergonomic controls optimized for use on the move. Lightweight construction and a secure strap make it a comfortable training companion. Metrics are presented clearly to help athletes track progress.',
    price: 169.5,
    currency: 'USD',
  },
  {
    id: 41,
    name: 'Astra Elite',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'Premium materials and refined movement.',
    description: 'Astra Elite elevates materials and movement quality for a more premium offering. Finely finished case surfaces and a reliable movement deliver a refined wearing experience. This watch is suited to those seeking discreet luxury and lasting construction.',
    price: 329.99,
    currency: 'USD',
  },
  {
    id: 42,
    name: 'Lumen Flex',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'Flexible strap and ergonomic case.',
    description: 'Lumen Flex focuses on comfort with a flexible strap and ergonomically shaped case that follows wrist movement. The watch is ideal for users who value comfort for all-day wear, with clean dial design and practical water resistance for everyday life.',
    price: 139.0,
    currency: 'USD',
  },
  {
    id: 43,
    name: 'Heritage Chrono',
    image: require('../images/watches/watch3.jpg'),
    short_description: 'Classic chronograph with clear subdials.',
    description: 'Heritage Chrono is a classic chronograph with stacked subdials, tactile pushers and a robust movement. The watch emphasizes timing precision and traditional design cues, making it a favorite for enthusiasts who appreciate mechanical charm and functional aesthetics.',
    price: 479.5,
    currency: 'USD',
  },
  {
    id: 44,
    name: 'Orbit Minimal Rose',
    image: require('../images/watches/watch4.jpg'),
    short_description: 'Rose-gold minimal watch, elegant and modern.',
    description: 'Orbit Minimal Rose pairs minimalist design with rose-gold accents for a contemporary, elegant look. The watch is balanced in proportion and detail, suitable for both everyday wear and more formal situations. Its subdued luxury is accessible and tasteful.',
    price: 209.0,
    currency: 'USD',
  },
  {
    id: 45,
    name: 'Rover Nomad',
    image: require('../images/watches/watch5.jpg'),
    short_description: 'Nomad series built for long travels.',
    description: 'Rover Nomad is engineered for travelers with a durable build and features focused on reliability and comfort. The watch combines navigational utility with a comfortable strap and protective case architecture. It is a travel-ready companion for long journeys.',
    price: 279.99,
    currency: 'USD',
  },
  {
    id: 46,
    name: 'Nova Spark',
    image: require('../images/watches/watch6.jpg'),
    short_description: 'Bright, colorful watch with smart notifications.',
    description: 'Nova Spark brings bright colorways and connected features together for a playful, functional watch. Notifications, simple fitness tracking and a lively design make it ideal for users who want personality in their wearable. Durable materials keep it ready for daily use.',
    price: 149.99,
    currency: 'USD',
  },
  {
    id: 47,
    name: 'Eclipse Classic',
    image: require('../images/watches/watch7.jpg'),
    short_description: 'Timeless design with refined detailing.',
    description: 'Eclipse Classic embodies timeless design with subtle detailing and high-quality finishes. The watch is versatile enough for daily wear while maintaining an elevated sense of style for special occasions, thanks to tasteful proportions and refined accents.',
    price: 679.0,
    currency: 'USD',
  },
  {
    id: 48,
    name: 'Trail Enduro',
    image: require('../images/watches/watch11.jpg'),
    short_description: 'Endurance-focused features and robust battery.',
    description: 'Trail Enduro emphasizes endurance with a robust battery and features tailored for long outdoor activities. Durable construction and focused functionality make it a strong choice for multi-day adventures and intensive training periods. Comfort and reliability are core strengths.',
    price: 249.5,
    currency: 'USD',
  },
  {
    id: 49,
    name: 'Astra Horizon',
    image: require('../images/watches/watch1.jpg'),
    short_description: 'Horizon series with dual-time functionality.',
    description: 'Astra Horizon offers dual-time functionality for travelers and professionals who need to track multiple time zones. The watch retains a refined look while providing practical utility for frequent flyers and international schedules. It pairs complexity with legible dial architecture.',
    price: 289.99,
    currency: 'USD',
  },
  {
    id: 50,
    name: 'Lumen Voyager',
    image: require('../images/watches/watch2.jpg'),
    short_description: 'Voyager edition with travel-friendly features.',
    description: 'Lumen Voyager is tuned for travel with practical features and a durable, compact design. The watch provides essential tracking and comfortable wear for long days on the move. Its versatile aesthetic makes it a dependable companion for journeys both near and far.',
    price: 169.0,
    currency: 'USD',
  },
];
